services:
  server:
    container_name: youvie_server
    image: devhackzone/youvie_server
    ports:
      - "5000:5000"
    env_file:
      - ./server_env
    environment:
      NODE_ENV: production
      PORT: 5000
    # Enable restart policy for reliability
    restart: always

  # ---------------------
  # NEXT.JS FRONTEND SERVICE (movie-app-client) - Port 3000
  # ---------------------
  client:
    container_name: youvie_client
    image: devhackzone/youvie_client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    
    env_file:
      - ./client_env
    depends_on:
      - server
    restart: always