services:
  # ---------------------
  # NESTJS BACKEND SERVICE (movie-app-server) - Port 5000
  # MUST be defined first so 'client' can reference it in env
  # ---------------------
  server:
    container_name: movie_app_server
    # Use the production Dockerfile context
    build:
      context: ./movie-app-server
      dockerfile: Dockerfile
    # Map host:container ports. Open 5000 externally for testing/direct access.
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    # Enable restart policy for reliability
    restart: always

  # ---------------------
  # NEXT.JS FRONTEND SERVICE (movie-app-client) - Port 3000
  # ---------------------
  client:
    container_name: movie_app_client
    build:
      context: ./movie-app-client
      dockerfile: Dockerfile
    # Map host:container ports. Open 3000 externally for browser access.
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # CRITICAL: Client needs to talk to the server container using its service name.
      # The client should use 'server:5000' for internal API calls.
      NEXT_PUBLIC_API_URL: http://server:5000
    # Client depends on server availability
    depends_on:
      - server
    restart: always